apiVersion: v1
kind: ConfigMap
metadata:
  name: ntfy
  namespace: ntfy
data:
  server.yml: |
    base-url: https://ntfy.k3s.simonhammes.cc
    behind-proxy: true

    auth-default-access: "deny-all"
    auth-file: "/var/lib/ntfy/user.db"
