apiVersion: v1
kind: Namespace
metadata:
  name: mariadb
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitnami
  namespace: mariadb
spec:
  interval: 10m
  type: oci
  url: oci://registry-1.docker.io/bitnamicharts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mariadb
  namespace: mariadb
spec:
  interval: 1m
  chart:
    spec:
      chart: mariadb
      version: 20.1.1
      sourceRef:
        kind: HelmRepository
        name: bitnami
      interval: 1m
