apiVersion: apps/v1
kind: Deployment
metadata:
  name: ntfy
  namespace: ntfy
spec:
  selector:
    matchLabels:
      app: ntfy
  template:
    metadata:
      labels:
        app: ntfy
    spec:
      containers:
      - name: ntfy
        # TODO: Add tag
        image: binwiederhier/ntfy
        args: [ "serve" ]
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
          name: http
        volumeMounts:
        - name: config
          mountPath: "/etc/ntfy"
          readOnly: true
        - name: database
          mountPath: /var/lib/ntfy
      volumes:
      - name: config
        configMap:
          name: ntfy
      - name: database
        persistentVolumeClaim:
          claimName: ntfy-database-pvc
