apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gatus
  namespace: gatus
spec:
  chart:
    spec:
      chart: gatus
      sourceRef:
        kind: HelmRepository
        name: gatus
  interval: 30m
  install:
    remediation:
      retries: 3
