apiVersion: v1
kind: Namespace
metadata:
  name: nginx
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitnami
  namespace: nginx
spec:
  interval: 10m
  type: oci
  url: oci://registry-1.docker.io/bitnamicharts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx
  namespace: nginx
spec:
  interval: 1m
  chart:
    spec:
      chart: nginx
      version: 18.2.6
      sourceRef:
        kind: HelmRepository
        name: bitnami
      interval: 1m
  values:
    service:
      type: ClusterIP
